apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: novaedge-leader-election-rolebinding
  namespace: novaedge-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: novaedge-leader-election-role
subjects:
- kind: ServiceAccount
  name: novaedge-controller
  namespace: novaedge-system
