apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novaedge-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: novaedge-controller-role
subjects:
- kind: ServiceAccount
  name: novaedge-controller
  namespace: novaedge-system
